### ISSUE TITLE
Search results get gray border

### ISSUE THREAD

**Issue by cloudlena** [pivotal-cf/docs-layout-repo#11]
Due to https://github.com/cloudfoundry/docs-book-cloudfoundry/commit/b4bf3b0eb15f2ab1fae356d8277d76a91c405117 the search results are now part of the `.content`. As children of an element with this class, all the tables which are used in the search result now get a gray boarder which looks kind of ugly. Can we remove this border for the search results?

**Comment by animatedmax** [comment]
Hi @mastertinner We've added this story to our tracker, here:  https://www.pivotaltracker.com/story/show/116579597

Thanks much!
