### ISSUE TITLE
Streamligned syntax highlighting

### ISSUE THREAD

**Issue by cloudlena** [pivotal-cf/docs-layout-repo#29]
I'm not sure how the syntax highlighting works in the current version and if that is supposed to be done in the Book or in the Layout Repo... Can you please enlighten me? In my opinion we should use highlight.js everywhere and not use own custom css solution. I saw, however, that we have some files of hightlight.js in the repo but when I update them with new languages to syntax-highlight, nothing happens...

**Comment by animatedmax** [comment]
Bookbinder uses [middleman-syntax](https://github.com/middleman/middleman-syntax), an extension for the Middleman that adds syntax highlighting with [Rouge](https://github.com/jneen/rouge). To add syntax highlighting to a topic, start a code block with ```LANGUAGE, where LANGUAGE is the language the code is written in.

Example: 

<pre>
```ruby
def my_cool_method(message)
  puts message
end
```
</pre>

You can also use erb tags (in a file with a .erb extension) to do the same thing: 

<pre>
<% code("ruby") do %>
def my_cool_method(message)
  puts message
end
<% end %>
</pre>

If you're having problems with a specific language or file, please let us know so we can try to reproduce the issue. Thanks!

**Comment by cloudlena** [comment]
Thanks, @animatedmax! I'm not sure why we are importing [Highlight.js](https://highlightjs.org/) in `source/javascripts/vendor/www/javascripts/highlight.pack.js` then. Are we still using that somewhere? The problem that I was having is that we would like to include Gradle syntax (e.g. [here](https://docs.developer.swisscom.com/tutorial-java/dependencies.html)) which doesn't seem to be supported by Rouge. But I think we can just use Groovy syntax to make it work.

**Comment by animatedmax** [comment]
I've created a story to investigate removing Highlight.js https://www.pivotaltracker.com/story/show/123116231
