### ISSUE TITLE
Search results get cut off in Safari

### ISSUE THREAD

**Issue by cloudlena** [pivotal-cf/docs-layout-repo#7]
Should I open this issue here?
https://github.com/cloudfoundry/docs-book-cloudfoundry/issues/38

**Comment by kimahoff** [comment]
Hi @mastertinner -- I think there's no need. We have this on our radar and are working to fix this and other search result issues. Thanks for the bump!

**Comment by cloudlena** [comment]
Perfect, thanks @kimahoff!
